export const states = [
  "All",
  "Bihar",
  "Madhya Pradesh",
  "Maharashtra",
  "Rajasthan",
  "Uttar Pradesh",
];

export const cities: Record<string, string[]> = {
  "All": ["All"],
  "Bihar": [
    "All",
    "Muzaffarpur",
    "Patna",
  ],
  "Madhya Pradesh": [
    "All",
    "Agar Malwa",
    "Alirajpur",
    "Anuppur",
    "Ashoknagar",
    "Balaghat",
    "Barwani",
    "Betul",
    "Bhind",
    "Bhopal",
    "Burhanpur",
    "Chhatarpur",
    "Chhindwara",
    "Damoh",
    "Datia",
    "Dewas",
    "Dhar",
    "Dindori",
    "Guna",
    "Gwalior",
    "Harda",
    "Hoshangabad",
    "Indore",
    "Jabalpur",
    "Jhabua",
    "Katni",
    "Khandwa",
    "Khargone",
    "Mandla",
    "Mandsaur",
    "Morena",
    "Narsinghpur",
    "Neemuch",
    "Panna",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Seoni",
    "Shahdol",
    "Shajapur",
    "Sheopur",
    "Shivpuri",
    "Sidhi",
    "Singrauli",
    "Tikamgarh",
    "Ujjain",
    "Umaria",
    "Vidisha",
  ],
  "Maharashtra": [
    "All",
    "Mumbai",
  ],
  "Rajasthan": [
    "All",
    "Jaipur",
    "Jodhpur",
  ],
  "Uttar Pradesh": [
    "All",
    "Agra",
    "Kanpur",
    "Lucknow",
    "Varanasi",
  ],
};
