"""Initial migration with indexes

Revision ID: 90c9f1189430
Revises: 
Create Date: 2026-07-09 20:05:11.175951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c9f1189430'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_id'), ['id'], unique=False)

    op.create_table('news_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('news_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_sources_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_sources_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_sources_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_sources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_sources_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_sources_state'), ['state'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=False)

    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('credibility_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_source_url'), ['source_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_news_articles_state'), ['state'], unique=False)

    op.create_table('ai_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(), nullable=True),
    sa.Column('meta_description', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('reading_time', sa.String(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('related_articles', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    with op.batch_alter_table('ai_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_results_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_results_id'))

    op.drop_table('ai_results')
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_state'))
        batch_op.drop_index(batch_op.f('ix_news_articles_source_url'))
        batch_op.drop_index(batch_op.f('ix_news_articles_source_id'))
        batch_op.drop_index(batch_op.f('ix_news_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_articles_id'))
        batch_op.drop_index(batch_op.f('ix_news_articles_district'))
        batch_op.drop_index(batch_op.f('ix_news_articles_department'))
        batch_op.drop_index(batch_op.f('ix_news_articles_category'))

    op.drop_table('news_articles')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('news_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_sources_state'))
        batch_op.drop_index(batch_op.f('ix_news_sources_name'))
        batch_op.drop_index(batch_op.f('ix_news_sources_id'))
        batch_op.drop_index(batch_op.f('ix_news_sources_district'))
        batch_op.drop_index(batch_op.f('ix_news_sources_department'))
        batch_op.drop_index(batch_op.f('ix_news_sources_category'))

    op.drop_table('news_sources')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_id'))

    op.drop_table('logs')
    # ### end Alembic commands ###
