"""Initial migration

Revision ID: c745faede9bf
Revises: 
Create Date: 2026-07-08 12:08:39.533788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c745faede9bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_results', 'summary')
    op.alter_column('news_articles', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_news_articles_city'), table_name='news_articles')
    op.create_index(op.f('ix_news_articles_category'), 'news_articles', ['category'], unique=False)
    op.create_index(op.f('ix_news_articles_department'), 'news_articles', ['department'], unique=False)
    op.create_index(op.f('ix_news_articles_district'), 'news_articles', ['district'], unique=False)
    op.alter_column('news_sources', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_news_sources_category'), 'news_sources', ['category'], unique=False)
    op.create_index(op.f('ix_news_sources_department'), 'news_sources', ['department'], unique=False)
    op.create_index(op.f('ix_news_sources_district'), 'news_sources', ['district'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sources_district'), table_name='news_sources')
    op.drop_index(op.f('ix_news_sources_department'), table_name='news_sources')
    op.drop_index(op.f('ix_news_sources_category'), table_name='news_sources')
    op.alter_column('news_sources', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_news_articles_district'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_department'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_category'), table_name='news_articles')
    op.create_index(op.f('ix_news_articles_city'), 'news_articles', ['district'], unique=False)
    op.alter_column('news_articles', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('ai_results', sa.Column('summary', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
